// with-vue-nuxt/app.vue
<template>
  <div style="text-align: center; margin-top: 50px">
    <h1>Para Modal Starter Template with Vue + Vite</h1>
    <button
      @click="openModal"
      style="padding: 10px 20px; font-size: 16px; cursor: pointer">
      Open Para Modal
    </button>
  </div>
</template>

<script setup lang="ts">
  import { onMounted, onUnmounted, ref } from "vue";
  import { createParaModalConnector } from "./para-modal-connector.tsx";
  import { para } from "./client/para.js";
  import Logo from "./assets/para-logo.svg";
  import { OAuthMethod } from "@getpara/react-sdk";
  import "./style.css";

  const modalConnector = ref<any>(null);

  onMounted(() => {
    const container = document.createElement("div");
    document.body.appendChild(container);

    modalConnector.value = createParaModalConnector(container, {
      para: para,
      onClose: () => {
        modalConnector.value?.close();
      },
      appName: "Para Modal Starter Template",
      logo: Logo,
      disableEmailLogin: false,
      disablePhoneLogin: false,
      oAuthMethods: Object.values(OAuthMethod),
      onRampTestMode: true,
      twoFactorAuthEnabled: false,
      theme: {
        backgroundColor: "#FFF",
        foregroundColor: "#000",
        accentColor: "#FF754A",
        mode: "light",
        font: "Inter",
      },
    });
  });

  onUnmounted(() => {
    modalConnector.value?.unmount();
  });

  const openModal = () => {
    modalConnector.value?.open();
  };
</script>

// with-svelte-vite/src/App.svelte
<script lang="ts">
  import { CapsuleModal, OAuthMethod } from "@getpara/react-sdk";
  import "@getpara/react-sdk/styles.css";
  import Logo from "./assets/para-logo.svg";
  import { para } from "./client/para";
  import { sveltify } from "svelte-preprocess-react";

  const react = sveltify({ CapsuleModal });
  let isModalOpen = false;
</script>

<div class="container">
  <h1>Para Modal Starter Template with Svelte Kit</h1>
  <button on:click={() => isModalOpen = true}>
    Open Para Modal
  </button>
  <react.CapsuleModal
    para={para}
    appName="Para Modal Starter Template"
    logo={Logo}
    disableEmailLogin={false}
    disablePhoneLogin={false}
    oAuthMethods={Object.values(OAuthMethod)}
    isOpen={isModalOpen}
    onClose={() => isModalOpen = false}
    onRampTestMode={true}
    twoFactorAuthEnabled={false}
  />
</div>

<style>
  .container {
    text-align: center;
    margin-top: 50px;
  }

  button {
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
  }
</style>
